# time range
start_year: 2021
end_year: 2100
birth_year: 1900
retirement_year: 2050

# Environment
mean_inflation: 2.2

# Your profile (numbers of a whole year)
# Job
start_income: 42000
# Assets
start_money: 10000
start_stocks: 0
start_gold: 0
start_entgeltpunkte: 0
# Investments
assets_stock_ratio: 0.2
assets_gold_ratio: 0.1
# Expenses
start_expenses: 15000  # total of expenses you had last year (not really needed?!)
flat_expenses: 6000
car_expenses: 1500
other_expenses: 3000
luxury_expenses: 3000
# Retirement
retirement_factor: 1  # How much should your expenses decrease in retirement ?
desired_money_buffer: 10000  # How much money do you want to have after end_year ?
# tax of last year for fine tuning
start_taxable_income: 32000
start_tax: 6700

# Simulation config
# include randomness in the simulation?
random: True
# modules included in simulation
module_list:
  - main.environment.Inflation
  - main.home.Flat
  - main.insurances.InsuranceHealth
  - main.insurances.InsuranceNursingCare
  - main.insurances.InsuranceUnemployment
  - main.insurances.InsurancePension
  - main.mobility.Car
  - main.other.LuxuryExpenses
  - main.other.OtherExpenses
  - main.taxes.Taxes
  - main.work.Job
  - main.assets.Money
  - main.assets.Stocks
  - main.assets.Gold
module_list_year_end:
  - main.assets.Investment
