# time range
start_year: 2021
end_year: 2100
birth_year: 1900
retirement_year: 2050

# Every number is with regard of a whole year
# Job
start_income: 10000
# Assets
start_money: 0
start_entgeltpunkte: 7
# Expenses
start_expenses: 5000  # total of expenses you had last year (not really needed?!)
flat_expenses: 1000
car_expenses: 400
other_expenses: 2000
luxury_expenses: 1000
# Retirement
retirement_factor: 1  # How much should your expenses decrease in retirement ?
desired_money_buffer: 1000  # How much money do you want to have after end_year ?
# for tax fine tuning
start_taxable_income: 5000
start_tax: 1000

# Simulation config
# include randomness in the simulation?
random: false
# modules included in simulation
module_list:
  - main.environment.Inflation
  - main.home.Flat
  - main.insurances.InsuranceHealth
  - main.insurances.InsuranceNursingCare
  - main.insurances.InsuranceUnemployment
  - main.insurances.InsurancePension
  - main.mobility.Car
  - main.other.LuxuryExpenses
  - main.other.OtherExpenses
  - main.taxes.Taxes
  - main.work.Job
