# Every number is with regard of a whole year

simulation:
  random: True
  start_year: 2021
  end_year: 2100

profile:
  class: profiles.profiles.FullInvestment
  birth_year: 2000
  retirement_year: 2060

modules:
  main.environment.Inflation:
    inflation_mean: 2.2
    inflation_std: 2
  main.work.Job:
    start_income: 42000
    unemployed_months: 0
    prob_lose_job: 0.01  # per month
    prob_find_job: 0.1  # per month
  main.home.Flat:
    class: main.expenses.InflationSensitive
    start_expenses: 6000
  main.mobility.Car:
    class: main.expenses.InflationSensitive
    start_expenses: 2000
  main.other.OtherExpenses:
    class: main.expenses.InflationSensitive
    start_expenses: 3000
  main.other.LuxuryExpenses:
    class: main.expenses.InflationSensitiveVariable
    start_expenses: 2000

  assets.stocks.Stocks:
    class: assets.investment.Standard
    start_money_value: 0
    gains_tax: 0.25
    exchange_fee: 0.005
    depot_costs: 0.002
    # MSCI WORLD since 1980 -- TODO exclude crisis events
    # Gross Total Return-Index includes dividends
    value_increase_mean: 0.092
    value_increase_std: 0.14
  assets.resources.Gold:
    class: assets.investment.Standard
    start_money_value: 0
    # no tax, if gold is hold longer than 1 year
    # differential tax on silver ~ 10% if bought, no tax if sold
    gains_tax: 0.
    exchange_fee: 0.05
    depot_costs: 0.01
    # Gold price since since 1950
    value_increase_mean: 0.076029
    value_increase_std: 0.231742
  main.investing.Investing:
    run_end_of_year: True
    assets_ratios:
      assets.stocks.Stocks: 0.4
      assets.resources.Gold: 0.1

  main.insurances.Health:
    fraction_of_income: 0.073  # 2020
    income_threshold: 56250  # €/year , 2020
  main.insurances.NursingCare:
    fraction_of_income: 0.0165  # 2020
    retirement_factor: 2
    income_threshold: 56250  # €/year , 2020
  main.insurances.Unemployment:
    fraction_of_income: 0.012  # half employer, half employee
    retirement_factor: 0
    income_threshold: 82800
    months_you_get_unemployment_money: 12
    salary_fraction: 0.5
  main.insurances.Pension:
    entgeltpunkte: 0  # your points
    rentenwert: 34.19  # €/Entgeltpunkt/month, 2020
    durchschnittseinkommen: 40551  # € per year, 2020
    fraction_of_income: 0.093  # 2020  (half employer, half employee)
    income_threshold: 82800  # € per year, 2020
  main.taxes.Taxes:
    tax_rates:
      - taxable_income: 9168
        tax_rate: 0.
      - taxable_income: 12168
        tax_rate: 0.04
      - taxable_income: 17168
        tax_rate: 0.1
      - taxable_income: 24168
        tax_rate: 0.147
      - taxable_income: 35168
        tax_rate: 0.2
      - taxable_income: 51168
        tax_rate: 0.25
      - taxable_income: 73168
        tax_rate: 0.303
      - taxable_income: 125168
        tax_rate: 0.355
      - taxable_income: 334168
        tax_rate: 0.405
      - taxable_income: 836168
        tax_rate: 0.43
    taxable_incomes:
      - main.work.Job
      - main.insurances.Pension
    tax_offsets:
      - main.insurances.Health
      - main.insurances.NursingCare
      - main.insurances.Pension
      - main.insurances.Unemployment

  events.crisis.OilCrisis1973:
    probability: 0.07
  crisis_2045:
    class: events.crisis.OilCrisis1973
    start_year: 2045
  crisis_2055:
    class: events.crisis.LostDecadeJapan1991
    start_year: 2055

  CurrentAccount:
    class: assets.bank.CurrentAccount
    run_end_of_year: True
    start_money_value: 1000
    penalty_interest_limit: 50000
    penalty_interest_rate: 0.05
    overdraft_rate": 0.0775
